# Generated by Django 3.2.6 on 2021-08-20 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('passphrase', models.CharField(max_length=100, unique=True)),
                ('secret', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
