# Generated by Django 3.2.6 on 2021-08-20 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_user_coinbaseproapidata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CoinbaseProApiData',
            new_name='Store',
        ),
    ]
