# Generated by Django 3.2.6 on 2021-08-21 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_coinbaseproapidata_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_ID', models.CharField(max_length=10)),
                ('funds', models.FloatField()),
                ('side', models.CharField(max_length=10)),
            ],
        ),
    ]
